version: '3.8'

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: zama-api
    environment:
      - REQUIRE_API_KEY=false
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: zama-nginx
    environment:
      - API_KEY=CHANGEME
      - API_HOST=api
      - API_PORT=8080
    ports:
      - "8081:80"
    depends_on:
      - api
